//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Repair_Shop.Entities
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Parts_To_Request
    {
        public int Tether_Id { get; set; }
        public int Request_Id { get; set; }
        public int Part_Id { get; set; }
        public int Count { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Service_Request Service_Request { get; set; }

        public static int getTetherId() {
            int lastTether = DBEntities.Instance.Parts_To_Request.Last().Tether_Id;

            return lastTether + 1;
        }
    }
}
